language: java

# With 3.0, Java8 or above
jdk:
  - openjdk8
  - openjdk11

arch:
  - ppc64le
  - amd64
   
# whitelist
branches:
  only:
    - master
    - "3.0"

before_install: 
  - mkdir -p /opt/maven
  - curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz|tar -xz --strip 1 -C /opt/maven
  - export MAVEN_HOME=/opt/maven
  - export PATH=${MAVEN_HOME}/bin:${PATH}
